from AnalyticsTests import AnalyticsTests
from CoreTests import CoreTests
from DeviceIOTests import DeviceIOTests
from EventsTests import EventsTests
from ImagingTests import ImagingTests
from MediaTests import MediaTests
from PTZTests import PTZTests
from PullpointTests import PullpointTests
from RecordingTests import RecordingTests
from ReplayTests import ReplayTests
from SearchTests import SearchTests
from Tests import Tests
